user_counter_homepage:
    path:     /
    defaults: { _controller: UserCounterBundle:Default:index }

user_info:
    path: /info/{userEmail}
    defaults: { _controller: UserCounterBundle:Default:info }
    
user_change_info:
    path: /change_info/{userEmail}
    defaults: { _controller: UserCounterBundle:InfoUpdate:infoUpdate }