UserCounterBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
            unique: true
        dob:
            type: date
        accountNumber:
            type: integer
        visits:
            type: integer
        reference:
            type: string
            length: 15
    lifecycleCallbacks: {  }
